### ISSUE TITLE
[Retail] Lua error upon login 

### ISSUE THREAD

**Issue by TreizeEU** [AcidWeb/REKeys#4]
I just turned on REKeys as Dragonflight season 1 starts later this week (so I don't have a keystone in my bags), and I noticed a lua error upon login:

It mentions the pinned character that I've been having issues getting to work correctly for other characters for quite a while, so I'm not sure if it's related to that or new entirely and due to patch 10.0.

`18x REKeys/REKeys.lua:405: attempt to index field '?' (a nil value)
[string "@REKeys/REKeys.lua"]:405: in function `FindKey'
[string "@REKeys/REKeys.lua"]:872: in function <REKeys/REKeys.lua:868>

Locals:
self = <table> {
 BestRun = 0
 GetKeystoneLink = <function> defined @REKeys/REKeys.lua:690
 MainNames = <table> {
 }
 RequestKeys = <function> defined @REKeys/REKeys.lua:439
 GetPinList = <function> defined @REKeys/REKeys.lua:722
 OnAddonMessageAK = <function> defined @REKeys/REKeys.lua:347
 FindKey = <function> defined @REKeys/REKeys.lua:374
 FillTooltip = <function> defined @REKeys/REKeys.lua:515
 MyRealm = "Terokkar"
 GetPrefixes = <function> defined @REKeys/REKeys.lua:739
 PartyNames = <table> {
 }
 RewardColors = <table> {
 }
 MyClass = "SHAMAN"
 MyFaction = "Alliance"
 MPlusDataReceived = true
 MyFullName = "Treize-Terokkar"
 OnAddonMessage = <function> defined @REKeys/REKeys.lua:314
 LDB = <table> {
 }
 ThrottleTimer = 0
 GetShortMapName = <function> defined @REKeys/REKeys.lua:705
 MyName = "Treize"
 Fill = true
 OptionsMenu = Frame {
 }
 FillChat = <function> defined @REKeys/REKeys.lua:627
 Settings = <table> {
 }
 GetMain = <function> defined @REKeys/REKeys.lua:851
 DB = <table> {
 }
 GetKeystoneLevelColor = <function> defined @REKeys/REKeys.lua:815
 KeyQueryLimit = false
 DungeonNames = <table> {
 }
 GetShortTime = <function> defined @REKeys/REKeys.lua:713
 ThrottleTable = <table> {
 }
 KeySearchDelay = <function> defined @REKeys/REKeys.lua:868
 GetAKStatus = <function> defined @REKeys/REKeys.lua:860
 GetRaiderIOScore = <function> defined @REKeys/REKeys.lua:823
 AceConfig = <table> {
 }
 GetBestRunString = <function> defined @REKeys/REKeys.lua:807
 GetFill = <function> defined @REKeys/REKeys.lua:772
 PartyCheck = <table> {
 }
 GetParsedBestRun = <function> defined @REKeys/REKeys.lua:791
 DataVersion = 17
 GetBestRun = <function> defined @REKeys/REKeys.lua:781
 OnLoad = <function> defined @REKeys/REKeys.lua:168
 FillSorting = <function> defined @REKeys/REKeys.lua:474
 OverrideNames = <table> {
 }
 UpdateMain = <function> defined @REKeys/REKeys.lua:881
 OnEvent = <function> defined @REKeys/REKeys.lua:178
 AltNames = <table> {
 }
 Outdated = false
 AffixSchedule = <table> {
 }
 DefaultSettings = <table> {
 }
 PinnedNames = <table> {
 }
 ParseChat = <function> defined @REKeys/REKeys.lua:893
 TooltipHeaderFont = REKeysTooltipHeaderFont {
 }
 Factions = <table> {
 }
}
dungeonCompleted = nil
keystone = nil
resetTimestamp = 580669
currentAffixes = <table> {
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
}
(for control) = 1
i = 1
affixes = <table> {
 1 = 9
 2 = 122
 3 = 14
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = <table> {
 1 = 9
 2 = 122
 3 = 14
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
GetOwnedKeystoneChallengeMapID = <function> defined =[C]:-1
RE = <table> {
 BestRun = 0
 GetKeystoneLink = <function> defined @REKeys/REKeys.lua:690
 MainNames = <table> {
 }
 RequestKeys = <function> defined @REKeys/REKeys.lua:439
 GetPinList = <function> defined @REKeys/REKeys.lua:722
 OnAddonMessageAK = <function> defined @REKeys/REKeys.lua:347
 FindKey = <function> defined @REKeys/REKeys.lua:374
 FillTooltip = <function> defined @REKeys/REKeys.lua:515
 MyRealm = "Terokkar"
 GetPrefixes = <function> defined @REKeys/REKeys.lua:739
 PartyNames = <table> {
 }
 RewardColors = <table> {
 }
 MyClass = "SHAMAN"
 MyFaction = "Alliance"
 MPlusDataReceived = true
 My`

**Comment by AcidWeb** [comment]
It will be updated tommorow.

**Comment by AcidWeb** [comment]
Fixed in 1.12.0.
