### ISSUE TITLE
Feature Request: Respond to !keys

### ISSUE THREAD

**Issue by filliph** [AcidWeb/REKeys#5]
I do prefer using "real" addons to handle functionality as opposed to WeakAuras, and following our WoWUIDev discussion earlier today, I think responding to `!keys` would be a valuable asset.

Basically, stealing AstralKeys' config options for responding to `!keys` would be perfect 🙂

**Comment by AcidWeb** [comment]
Hmmm...

<img width="159" alt="image" src="https://user-images.githubusercontent.com/3713734/212392552-a4251df3-7164-4104-a0ce-6bf5ad90f6dc.png">

**Comment by filliph** [comment]
Ah, I hadn't installed this add-on and I didn't see it in the feature list, that's why I suggested it 😅 

Does it also support configuring whether to output to guild or party (or both)?

**Comment by AcidWeb** [comment]
Destination of response is based on the source of `!keys`.

**Comment by filliph** [comment]
Right, but AstralKeys and the weakaura have the option to not respond in either party or guild chat, there could be some value in that as well 🙂

**Comment by AcidWeb** [comment]
Maybe I will add it.
